### PR TITLE
UsageGenerator

### PR DESCRIPTION
**Pull request by rjacolin**

### CODE REVIEW

**Comment by sebz** [comment]
@rjacolin I just pushed the refactoring to integrate the `DailyUsageEngine` as a proper engine.

To use it, my config looks like:

``` json
{
    "name": "Usages",
    "label": "virtual-sims",
    "fleet": {
        "size": 1,
        "namePrefix": "VSIMs #"
    },
    "generation": {
        "mode": "dailyUsage"
    },
    "clean": false
}
```

I let you review my modifications and make some tests :smile:

**Comment by rjacolin** [comment]
In factory:

**Comment by rjacolin** [comment]
In factory.js:
`else {
        // No application => SIM Usage simulation
        system.subscription = {
            identifier: Math.floor(Math.random() * 1000000000),
            operator: "SIERRA_WIRELESS"
        };
    }`

that mean you create only Sierra Sims?

**Comment by sebz** [comment]
Indeed, the `operator` could be a configuration param.

**Comment by rjacolin** [comment]
Nothing more. Tested successfully today.

**Pull request merged**
